server:
  port: 9986

spring:
  datasource:
    url: jdbc:mysql://139.199.36.234:3566/cubic?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: yfteSt196._css996_pUs;asdDTPDsd
    driver-class-name: com.mysql.jdbc.Driver
  security:
    basic:
      enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cubic.root.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
