server:
  port: 9986
spring:
  datasource:
    url: jdbc:mysql://ip:port/databases?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  security:
    basic:
      enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cubic.root.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
